services:
  api:
    image: rafhs/colibri-api:latest
    container_name: colibri-api
    expose:
      - "4000"

  nginx:
    image: nginx:1.27-alpine
    container_name: colibri-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
